### ISSUE TITLE
Errors with {proxy: false} and multiple connections

### ISSUE THREAD

**Issue by jmm** [bendrucker/hapi-require-https#17]
Hi, FYI this throws when `proxy: false` and there's more than one connection configured. Here's a [minimal repro](https://github.com/jmm/hapi-require-https-conn-repro/tree/master).

Looks like what you want is:

```diff
- : request.server.info.protocol === 'http'
+ : request.connection.info.protocol === 'http'
```

I opened an issue on hapi about documenting `request.connection`: https://github.com/hapijs/hapi/issues/3328

Also, this seems only likely to work when using default ports. Otherwise it would be redirecting to https on the same port that http was requested on.

**Comment by bendrucker** [comment]
Good catch! Fix passes tests all the way back to Hapi 8 so it definitely seems perfectly safe to use.

**Comment by jmm** [comment]
Cool, thanks!
