### ISSUE TITLE
Require HTTP does not redirect

### ISSUE THREAD

**Issue by CelsoSantos** [bendrucker/hapi-require-https#18]
Hello,

I've installed this module, setted it up by using proxy: false (since I'm testing locally) but for some reason I'm never redirected.
How come?

The service starts and all, but whenever I try to go to http://localhost:9443/restricted I'm never redirected. I explicitly need to insert the https.

I'm running on Node v4.5 and trying to access the site on Chrome Version 52.0.2743.116 (64-bit)

Here's my code. Also, I don't envs settup so it's using 0.0.0.0:9443:

```
var HapiRequireHTTPS = require('hapi-require-https');
var ServiceRoutes = require("./routes/service");

var server = new Hapi.Server();
var PORT = process.env.PORT || 9443;
var HOST = process.env.SERVICE_HOST || '0.0.0.0';

server.connection({
	labels: 'https',
	port: PORT,
	host: HOST,
	tls: {
            key: Fs.readFileSync(__dirname + '/../certs/mycert.com.key'),
            cert: Fs.readFileSync(__dirname + '/../certs/mycert.com.crt')
        },
	routes: {
		cors: {
			origin: ['*'],
			headers: ["Accept", "Authorization", "Content-Type", "If-None-Match", "Accept-language"],
			exposedHeaders: ["Authorization"]
		}
	}
});

let plugins = [
	{
		register: HapiRequireHTTPS,
		options: { proxy: false }
	}
]

server.register(plugins, function (err) {
	if (err) {
		console.error(err);
		process.exit(1);
	}

	//Initialize Routes on the server
	server.route(ServiceRoutes);
})
```

**Comment by bendrucker** [comment]
That's a lot of code for me to parse. The plugin is pretty dead simple so I'd recommend just stepping through it. If you make a smaller reproduction I'd be happy to try running it but it'd have to be shorter and not require transpilation

**Comment by CelsoSantos** [comment]
I can remove all other code aside from the one related to RequireHttps, it won't really make a big difference.
The issue here is that it does never redirect http calls to https automatically as I was expecting. I'm running the service locally via `node <script_path>` and accessing http won't redirect to https.

The code was just to make sure that there was nothing wrong with the configuration (which I don't think it does).

I'm not behind nginx or anything of the like. Just running locally. Shouldn't the plugin work anyway?

**Comment by bendrucker** [comment]
Ah, got it. You're only creating an HTTPS connection. You need to create an HTTP connection and HTTPS and apply the redirect plugin to the HTTP connection.

**Comment by CelsoSantos** [comment]
Hello again @bendrucker .

That was indeed the issue, thank you.
I'm reopening the ticket just because of one thing:
If my http server listens on port 8080 and my https on port 8443 (examples), and I try to access the site via http://local.myproject.com:8080 I am indeed redirected to https but the port stays there (http://local.myproject.com:8080), never changing it to https://local.myproject.com:8443.

This is because the `request.headers.host` comes populated with the port. Any chance we could force changing the port? Would you evaluate a PR with this change?

Best Regards,
Celso Santos

**Comment by bendrucker** [comment]
No, force changing the port is not an appropriate feature for the library. In production everyone will have something, even if it's a load balancer and not the app itself, listening on 80/443. This library assumes you're using the default ports and that redirecting will take care of that. Anything else is custom enough that it's best to just do a custom plugin if for some reason you really intended to use custom ports.
