### ISSUE TITLE
Glue interface

### ISSUE THREAD

**Issue by jberall** [bendrucker/hapi-require-https#21]
I'm using glue and it doesn't seem to be responding.
        
 {
             plugin: 'hapi-require-https'
 },

Does the plugin require h202 (the proxy component installed.)
Thanks

**Comment by bendrucker** [comment]
Hey I've never looked at glue and don't understand the followup fragment/question. There's not much code here so I imagine you can figure it out. I'm going to close this since I don't plan to work on it further but I'm happy to continue discussion or review a PR if you figure out what's up.
