### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by XhmikosR** [bendrucker/hapi-require-https#35]
@bendrucker this is how I'm trying to use the plugin https://github.com/mozilla/srihash.org/compare/xmr-redirect-www

When I console.log `PLUGINS`, I see this:

```
[
  {
    plugin: {
      name: 'vision',
      multiple: true,
      pkg: [Object],
      requirements: [Object],
      register: [Function: register]
    }
  },
  {
    plugin: {
      name: 'inert',
      pkg: [Object],
      once: true,
      requirements: [Object],
      register: [Function: register]
    }
  },
  { register: [Function: register], name: 'hapi-require-https' }
]
```

Admittedly I'm trying to test this locally, and when I made the initial patch, we were using Hapi 16. But I'd swear this worked in the past locally.

Maybe I'm doing something wrong?

Thanks in advance!

**Comment by bendrucker** [comment]
That is a perfectly valid input to server.register. This is just a rehash of your comment on the PR and I can’t provide general Hapi support for you. 

If you find a specific error that suggests that there is something wrong with this package I’m happy to look.
