### ISSUE TITLE
update to hapi 9

### ISSUE THREAD

**Issue by k-sheth** [bendrucker/hapi-require-https#5]
When I upgrade to hapi 9, and reinstall all my dependencies I get the following error
npm ERR! peerinvalid The package hapi does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer hapi-require-https@2.0.0 wants hapi@8

I am using
node v0.12.7
npm v2.11.3

Thanks

**Comment by bendrucker** [comment]
Would really appreciate a PR instead of an issue!
